### PR TITLE
Lava slave aarch64

### PR DESCRIPTION
**Pull request by EmbeddedAndroid**

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Pull request merged**
